accounts/urls.py
from django.urls import path
from .views import(
    account_signup,
    account_login,
    account_otp,
    account_signout,
    account_signout_confirm,
    contact,
    orders,
    success,
    terms,
    )

app_name = 'accounts'

urlpatterns = [
    path('account_signup/', account_signup, name='account_signup'),
    path('account_login/', account_login, name='account_login'),
    path('account_otp/', account_otp, name='account_otp'),
    path('account_signout/', account_signout, name='account_signout'),
    path('account_signout_confirm/', account_signout_confirm, name='account_signout_confirm'),
    path('contact/', contact, name='contact'),
    path('orders/<int:pk>/', orders, name='orders'),
    path('success/', success, name='success'),
    path('terms/', terms, name='terms'),
]

bibz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from core.views import search
# from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login/', LoginView.as_view()),
    path('accounts/', include('accounts.urls',  namespace='accounts')),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/accounts/success/'), name='password_reset_confirm'),
    # path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('', include('core.urls', namespace='core')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),

    path('search/', search,name='search'),


]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/admin_login/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://fonts.googleapis.com/css?family=Anton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <link rel="icon" href="{% static 'img/favicon.png' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Admin</title>
</head>
<body>
<main><link href="{% static 'css/formss.css' %}" rel="stylesheet">
<div class="container">
      <section class="mt-2 pt-2">
        <div class="row wow fadeIn">
        <div class="card m-1  mx-auto p-4" style="width:500px!important;">

            <h1>Sign In</h1>
            <p> If you have not created an account yet,
             <a href="{% url 'accounts:account_signup' %}" style="color:#007e92;">Sign up</a></p>

            <form action="{% url 'accounts:account_login' %}" method="post">
                {% csrf_token %}
                <div>
                    <input type="text" name="uname" id=""  class="form-control mt-2" required>
                    <label>Username<span>*</span></label>
                </div>

                <div>
                    <input type="password" name="pass" id=""  class="form-control" required>
                    <label>Password<span>*</span></label>
                </div>

                <div>
                    <a style="width:170px!important;" type="submit" value=" " class=" btn btn-default" href="{% url 'password_reset' %}">forgot password?</a>
                    <input type="submit" value="Login" class="btn btn-primary">
                </div>

            </form>
          </div>
        </div>
      </section>
</div>
</main>

</body>
</html>