accounts/urls.py
from django.urls import path
from .views import(
    account_signup,
    account_login,
    account_otp,
    account_signout,
    account_signout_confirm,
    contact,
    orders,
    success,
    terms,
    )

app_name = 'accounts'

urlpatterns = [
    path('account_signup/', account_signup, name='account_signup'),
    path('account_login/', account_login, name='account_login'),
    path('account_otp/', account_otp, name='account_otp'),
    path('account_signout/', account_signout, name='account_signout'),
    path('account_signout_confirm/', account_signout_confirm, name='account_signout_confirm'),
    path('contact/', contact, name='contact'),
    path('orders/<int:pk>/', orders, name='orders'),
    path('success/', success, name='success'),
    path('terms/', terms, name='terms'),
]

bibz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from core.views import search
# from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('login/', LoginView.as_view()),
    path('accounts/', include('accounts.urls',  namespace='accounts')),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'),name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/accounts/success/'), name='password_reset_confirm'),
    # path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),
    path('', include('core.urls', namespace='core')),
    path('adminapp/', include('adminapp.urls', namespace='adminapp')),

    path('search/', search,name='search'),


]

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from .views import (
    # ItemDetailView,
    item_detail,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    add_single_item_to_cart,
    AddCouponView,
    RequestRefundView,
    PaymentcodView,
    accounts,
    accountsedit,
    handlerequest,
    back,
    add_to_wish_list,
    remove_from_wish_list,
    wish_lists,
    # homes
)

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    # path('', homes, name='homes'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', item_detail, name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('add_single_item_to_cart/<slug>/', add_single_item_to_cart, name='add_single_item_to_cart'),
    path('paymentcod/<payment_option>/', PaymentcodView.as_view(), name='paymentcod'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('accounts/', accounts, name='accounts'),
    path('accountsedit/', accountsedit, name='accountsedit'),
    path('handlerequest/', handlerequest, name="HandleRequest"),
    path('back/', back, name="back"),

    path('add-to-wish-list/<slug>/', add_to_wish_list, name="add_to_wish_list"),
    path('remove-from-wish-list/<slug>/', remove_from_wish_list, name="remove_from_wish_list"),
    path('wishlists/', wish_lists, name="wish_lists"),


]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class ExtendedUser(models.Model):
    phone_num=models.CharField(max_length=15)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

core/models.py
from django.conf import settings
from django.db import models
from django.shortcuts import reverse


SIZE_CHOICES = (
    ('S', 'Small'),
    ('M', 'Medium'),
    ('L', 'Large'),
    ('XL', 'Extra large'),
    ('XXL', 'X-Extra large')
)


LABEL_CHOICES = (
    ('White', 'White'),
    ('Yellow', 'Yellow'),
    ('Blue', 'Blue'),
    ('Red', 'Red'),
    ('Green', 'Green'),
    ('Black', 'Black'),
    ('Brown', 'Brown'),
    ('Azure', 'Azure'),
    ('Ivory', 'Ivory'),
    ('Teal', 'Teal'),
    ('Silver', 'Silver'),
    ('Purple', 'Purple'),
    ('Navy blue', 'Navy blue'),
    ('Pea green', 'Pea green'),
    ('Gray', 'Gray'),
    ('Orange', 'Orange'),
    ('Maroon', 'Maroon'),
    ('Charcoal', 'Charcoal'),
    ('Aquamarine', 'Aquamarine'),
    ('Coral', 'Coral'),
    ('Fuchsia', 'Fuchsia'),
    ('Wheat', 'Wheat'),
    ('Lime', 'Lime'),
    ('Crimson', 'Crimson'),
    ('Khaki', 'Khaki'),
    ('Hot pink', 'Hot pink'),
    ('Magenta', 'Magenta'),
    ('Olden', 'Olden'),
    ('Plum', 'Plum'),
    ('Olive', 'Olive'),
    ('Cyan', 'Cyan'),
)


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    label = models.CharField(choices=LABEL_CHOICES, max_length=20)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    image1 = models.ImageField(blank=True, null=True)
    image2 = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={'slug': self.slug})


class Variation(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    size = models.CharField(max_length=120, choices=SIZE_CHOICES)

    def __unicode__(self):
        return self.size


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    size = models.ForeignKey(Variation, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    def get_taxable_amount(self):
        if self.item.discount_price:
            # return int(self.get_total_discount_item_price()-(self.get_total_discount_item_price()*(tax/100)))
            taxable = self.get_total_discount_item_price() / 1.18
            taxable_amount = round(taxable, 2)
            return taxable_amount
        else:
            taxable = self.get_total_item_price() / 1.18
            taxable_amount = round(taxable, 2)
            return taxable_amount

    def get_tax_amount(self):
        if self.item.discount_price:
            taxable = self.get_total_discount_item_price() * 18 / 118
            taxable_amount = round(taxable, 2)
            return taxable_amount
        else:
            taxable = self.get_total_item_price() * 18 / 118
            taxable_amount = round(taxable, 2)
            return taxable_amount


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment_mode = models.CharField(max_length=20, default='NOT PROCESSED')
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    phone = models.CharField(max_length=13)
    state = models.CharField(max_length=100)
    zip = models.CharField(max_length=100)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    order_id = models.CharField(max_length=255)
    txn_id = models.CharField(max_length=255)
    txn_amount = models.CharField(max_length=255)
    pmt_mode = models.CharField(max_length=255)
    txn_date = models.DateTimeField(auto_now_add=True)
    txn_status = models.CharField(max_length=255)

    def __str__(self):
        return self.user.username


class WishList(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

accounts/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import auth, messages
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import ExtendedUser
import random
from django.contrib.auth.decorators import login_required
from core.models import Order, Address
import requests
from django.core.mail import send_mail


def homepage(request):
    return render(request, 'login.html')


def account_login(request):
    if request.method == "POST":
        user = auth.authenticate(username=request.POST['uname'], password=request.POST['pass'])
        if user is not None:
            auth.login(request, user)
            messages.success(request, 'You have logged in successfully')
            return redirect('/')
        else:
            messages.warning(request, "Invalid Login credentials.")
            return redirect('accounts:account_login')
    else:
        return render(request, 'account_login.html')


def account_signup(request):
    if request.method == "POST":
        if request.POST['pass'] == request.POST['passwordagain']:
            if User.objects.filter(username=request.POST['uname']).exists():
                messages.warning(request, 'Username has already taken')
                return render(request, 'account_signup.html')

            elif User.objects.filter(email=request.POST['email']).exists():
                messages.warning(request, 'Email has already taken, please type your exact email address')
                return render(request, 'account_signup.html')
            else:
                # user = User.objects.create_user(username=request.POST['uname'], password=request.POST['pass'])

                username = request.POST['uname']
                email = request.POST['email']
                password = request.POST['pass']
                phone = request.POST['phone']
                # newextendeduser = Extendeduser(phone_num=phone,age=age, user=user)
                print()
                generated_otp = random.randint(1111, 9999)
                print('generated otp is ', generated_otp)

                url = "https://www.fast2sms.com/dev/bulk"
                payload = "sender_id=FSTSMS&message=hi your OTP is {} &language=english&route=p&numbers={}".format(
                    generated_otp,
                    phone)
                headers = {
                    'authorization': "4x3CrQ8w8qX4ak577JiULwXK1ke1IhmE8oTjejcvGV74vg4yxacfL7GtM1jF",
                    'Content-Type': "application/x-www-form-urlencoded",
                    'Cache-Control': "no-cache",
                }
                response = requests.request("POST", url, data=payload, headers=headers)

                return render(request, 'account_otp.html',
                              {'generated_otp': generated_otp, 'phone': phone, 'username': username, 'email': email,
                               'password': password})

        else:
            messages.warning(request, "Password didn't match")
            return render(request, 'account_signup.html')
    else:
        return render(request, 'account_signup.html')


def account_otp(request):
    if request.method == "POST":
        user_otp = request.POST["otp"]
        generated_otp = request.POST["generated_otp"]
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        phone = request.POST["phone"]

        if user_otp == generated_otp:
            user = User.objects.create_user(username=username, email=email, password=password)
            newextendeduser = ExtendedUser(phone_num=phone, user=user)
            newextendeduser.save()
            auth.login(request, user)
            messages.success(request, 'Your BIBZ account is created')
            return redirect('/')
        else:
            messages.info(request, "hey! you typed invalid otp try again ")
            return render(request, 'account_otp.html.',
                          {'generated_otp': generated_otp, 'phone': phone, 'username': username, 'email': email,
                           'password': password})
    return render(request, 'account_otp.html')


def account_signout(request):
    return render(request, 'account_signout.html')


def account_signout_confirm(request):
    logout(request)
    messages.info(request, "Logged out successfully!")
    return redirect('/')


def contact(request):
    if request.method == "POST":
        fname = request.POST['firstname']
        lname = request.POST['lastname']
        email = request.POST['email']
        sub = request.POST['subject']

        sender = "vishnusumavausinfotech@gmail.com"
        receiver = ["info@vausinfotech.com", "dilipsapkota.d@gmail.com", "neelakanth@vausinfotech.com"]
        message = "\nfirst name:" + fname + "\nlast name: " + lname + "\nemail: " + email + "\nmessage: " + sub
        print('full message:', message)

        send_mail('Enquiry related BIBZ', message, sender, receiver)
        messages.success(request, 'Thanks You for being touched with us, our team will respond back you..')
    return render(request, 'contact.html')


def orders(request, pk):
    order = get_object_or_404(Order, id=pk)
    address = Address.objects.filter(user=request.user)[0]
    obj = User.objects.get(id=request.user.id)
    phone = ExtendedUser.objects.get(user=obj)
    return render(request, 'orders.html', {'order': order, 'address': address, 'address_phone': phone})


def success(request):
    messages.success(request, "Your password reset done successfully")
    return redirect('accounts:account_login')


def terms(request):
    return render(request, 'terms.html')

templates/accounts.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<main>

    <!-- new order list htmls-->

    <div class="container">
        <div class="row">
            <div class="col-12 mt-3 col-md-4" style="padding:10px;">
                <div class="contact_body"
                    <div class="card text-center contact_top">
                        <h1 class="contact_header pt-2"><i class="fa fa-user-circle" class="" aria-hidden="true"></i>
                        </h1>
                        <p class="mt-1"><b style="text-transform:capitalize;">{{ request.user }}</b><br>
                            {{ phone.phone_num }}<br>
                            {{ request.user.email }}<br>
                        </p>
                    </div>
                    <div class="card my-3 p-0 text-center">
                        <div class="pt-3" style="background:#E1E0E0;border-radius:5px 5px 0px 0px;"><b> Default
                            Address </b></div>
                        <p class="mt-1">
                            {% if address %}
                            {{ address.street_address }}<br>
                            {{ address.apartment_address }}<br>
                            {{address.state}} - {{ address.zip }}<br>
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-8 mx-auto" style="padding:10px;">
                {% for i in ordered %}
                <div class="card p-3 my-3">
                    <div>
                        <a class="float-right" href="{% url 'accounts:orders' pk=i.id %}"><h5 class="linking">Order
                            details </h5></a>
                        <h5>Order placed on:&nbsp{{i.ordered_date}}</h5>
                        <h5>Order ID:{{ i.id }}</h5>
                    </div>
                    <div class="justify-content-between">{% for j in i.items.all %}
                        <div class="flex-container flex-row" style="display:flex;">
                            <div class="d-flex flex-row">
                                <div class="pb-1">
                                    <img class="" src="{{j.item.image.url}}" width="100px" height="100px" alt="">
                                </div>
                                <div class="pl-4 pb-1">
                                    <p>{{j.item}}<br>
                                        Size:{{j.size.size}}<br>
                                        Quantity:{{j.quantity}}<br>
                                        Price:{{ j.item.price }}
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="d-flex justify-content-end">
                            {% if i.received %}
                            <p style="color:green!important;">Order Delivered</p>
                            {% else %}
                            <p style="color:red!important;">Being Delivered . . .</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/footer.html
{% load static %}

<footer class="page-footer  font-small mt-4 wow fadeIn">
    <div clss="" style="background:#7E94AA;">
        <div class="container" style="color:#082340;">
            <div class="row pt-1 flex-container text-center my-auto">
                <div class="col-4 mx-auto">
                    <h4><i  class=" fas fa-exchange-alt"></i></h4>
                    <h5>EASY EXCHANGE</h5>
                </div>
                <div class="col-4 mx-auto ">
                    <h4><i  class=" fas fa-hand-holding-heart"></i></h4>
                    <h5>100% HAND PICKED</h5>
                </div>
                <div class="col-4 mx-auto">
                    <h4><i class="fas fa-certificate"></i></h4>
                    <h5>ASSURED QUALITY</h5>
                </div>
            </div>
        </div>
    </div>

    <div class="container-field">
    <div class="container  pt-2 my-auto px-3" >
        <div class="row mt-3">
        <div class="col-6 col-md-3 col-lg-3 lists">
            <ol>{% if request.user.is_authenticated %}
                <h6>My BIBZ</h6>
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'core:accounts' %}">My Account</a></li>
                <li><a href="{% url 'core:wish_lists' %}">My Wishlist</a></li>
                <li><a href="{% url 'core:accounts' %}">My Orders</a></li>
                <li><a href="{% url 'core:order-summary' %}">My Cart</a></li>
                {% else %}
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'accounts:account_login' %}">My Account</a></li>
                <li><a href="{% url 'accounts:account_login' %}">My Wishlist</a></li>
                <li><a href="{% url 'accounts:account_login' %}">My Orders</a></li>
                <li><a href="{% url 'accounts:account_login' %}">My Cart</a></li>
                {% endif %}
            </ol>
        </div>
        <div class="col-6 col-md-3 col-lg-3 lists ">
            <ol class="ol1">
                <h6>Social Communities</h6>
                <a href="https://www.facebook.com/" target="_blank"> <i class="px-1 fab fa-facebook-f"></i></a>
                <a href="https://www.instagram.com/?hl=en" target="_blank"></a><i class="px-1 fab fa-instagram"></i>
                <a href="https://www.whatsapp.com/" target="_blank"></a><i class="px-1 fab fa-whatsapp"></i>
                <a href="https://twitter.com/login" target="_blank"></a><i class="px-1 fab fa-twitter"></i>
            </ol>
        </div>
        <div class="col-6 col-md-3 col-lg-3 lists ">
            <ol>
                <h6>Help</h6>
                <li><a href="{% url 'accounts:contact' %}"><i class=" fa fa-envelope" aria-hidden="true"></i> - email@email.com</a></li>
                <li><a href="https://www.whatsapp.com/" target="_blank"><i class=" fab fa-whatsapp"></i> - 08042045246</a></li>
            </ol>
        </div>
        <div class="col-6 col-md-3 col-lg-3 lists ">
            <ol>
                <h6>Reach Us</h6>
                <li><a href="{% url 'accounts:contact' %}">Google Map &nbsp<i class="fa fa-link" aria-hidden="true"></i></a></li>
                <li><p>70/9 Channakrishnappa Building<br> Thindlu Main Road K Veeranna Layout Vidyaranyapura Post<br> Bangalore - 560097<br>
                MOB - 08042045246</p></li>
            </ol>
        </div>

        </div>
    </div>
    </div>



    <div clss="container-field">
        <div class="container">
        <div class="row">
        <div class="col-12 col-md-4 col-lg-4 my-auto" style="color:white;">
            <h6 class="pay">Payment methods</h6>
                <div class="flex-container my-auto">
                    <h6>Net <h6 class="banking">Banking</h6></h6>
                    <h6 class="px-2"><i class="fab fa-cc-visa"></i></h6>
                    <h6 class="px-1"><i class="fa fa-credit-card" aria-hidden="true"></i></h6>
                    <h6 class="px-1">Paytm</h6>
                    <h6 class="px-1">COD</h6>
                </div>
        </div>
        <div class="col-12 col-md-8 col-lg-8 my-auto " style="color:white;">
            <h6 class="">POLICY</h6>
            <div class="flex-container my-auto">
                <p><a href="{% url 'accounts:terms' %}" >Conditions of Use & Sale</a> </p>
                <p class="px-2"><a href="" >Return Policy</a></p>
                <p class="px-1"><a href="" >Privacy policy</a></p>
                <p class="px-1"><a href="" >Disclaimer</a></p>
            </div>
        </div>
        </div>
        </div>
    </div>

    <!--Payment details -->

    <!--Copyright-->
    <div clss="" style="padding-top:5px;">
        <div class="" style="color:white;">
            <div class="flex-container my-auto">
                <div class="mx-auto ">
                    © 2019 Copyright BIBZ.COM
                </div>
            </div>
        </div>
    </div>
    <!--/.Copyright-->


  </footer>

templates/home.html
{% extends "base.html" %}
{%  load static %}
{% block content %}

<main>

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <div class="container">

<!--  search field    -->
    <div class="row">
            <div class="col-12">
                <form class="form-inline float-right" action="/search/" method="post">
                {% csrf_token %}
                <input class="searching mr-sm-2" type="text" name="srh" placeholder="Search" aria-label="Search">
                <button type="submit"class="btn btn-primary">Search</button>
                </form>
            </div>
    </div>
<!--  search field    -->

<!--            for search items       -->
       <div class="container">
           <div class="row">
            {% if sr %}
            {% for item in sr %}
          <div class="col-6 col-lg-3 col-md-6 mb-4 procol">

              <div class="card product">

              <div class="view overlay">
              <div class="innerimage">
                <img src="{{ item.image.url }}" class="card-img-top">

                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
                  <div class="on_image">
                    <a href="{% url 'core:add_to_wish_list' slug=item.slug %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                </div>
              </div>
              </div>

              <div class="card-body card-body1 text-center">
<!--                <a href="" class="grey-text">-->
<!--                  <h5>{{ item.get_category_display }}</h5>-->
<!--                </a>-->
                <div class="item_title mx-auto"
                    <a style="overflow" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}

                    </a>
                </div>
<!--                  <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>-->

                <h6 class="font-weight-bold pt-2">
                  <strong>₹
                  {% if item.discount_price %}
                <del>₹{{ item.price }}</del>
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                  </strong>
                </h6>

              </div>

            </div>

          </div>
          {% endfor %}
          {% endif %}
       </div>
    </div>
<!--            search items ends       -->

    <section class="text-center mb-4 mt-1">
        <div class="row wow fadeIn">

 {% if object_list %}

            {% if not page_obj.has_previous %}
             {% include "carousel.html" %}

            {% endif %}

          {% for item in object_list %}

          <div class="col-6 col-lg-3 col-md-6 mb-4 procol">

              <div class="card product">

              <div class="view overlay">
                {% comment %} <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top img-fluid" {% endcomment %}
              <div class="innerimage">
                <img src="{{ item.image.url }}" class="card-img-top">

                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
                <div class="on_image">
                    <a href="{% url 'core:add_to_wish_list' slug=item.slug %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                </div>
              </div>
              </div>

              <div class="card-body card-body1 text-center">
<!--                <a href="" class="grey-text">-->
<!--                  <h5>{{ item.get_category_display }}</h5>-->
<!--                </a>-->
                <div class="item_title mx-auto"
                    <a style="overflow" href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}</a>
                </div>
<!--                  <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>-->

                <h6 class="font-weight-bold pt-2">
                  <strong>
                  {% if item.discount_price %}
                <del>₹{{ item.price }}</del>
                  ₹{{ item.discount_price }}
                  {% else %}
                  ₹{{ item.price }}
                  {% endif %}
                  </strong>
                </h6>
              </div>

            </div>

          </div>
          {% endfor %}
      {% endif %}
        </div>

      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        <li class="page-item ">
            {% if page_obj.has_previous %}
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Prev</a>
            {% endif %}
        </li>
        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
        <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-2' and num < page_obj.number|add:'2' %}
        <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
            {% endfor %}
        <li class="page-item">
        {% if page_obj.has_next %}
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}
        </li>
        </ul>
      </nav>
      {% endif %}
    </div>
  </main>

{% endblock content %}